project:
  artifactId: spry
  name: spry
  version: X.X.X.X
  description: spry

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  spring:
    profiles: ${spring.profiles.active:default}
  app:
    name: ${vcap.application.name:com.gospry}:${vcap.application.instance_index:*}
    start: ${vcap.application.start:N/A}

spring:
  main:
    sources: com.gospry.api.Application
  jpa:
    show_sql: false
    # org.hibernate.dialect.MySQL5InnoDBDialect or org.hibernate.dialect.HSQLDialect
    # FIX to remove error messages
    database-platform: com.gospry.api.helper.HSQLDBDialect
#  jpa.hibernate:


security:
  basic:
    enabled: true
  require_ssl: false
  enable_csrf: false
  ignored:
    - /register/**
    - /acitivate/**
    - /status
  # always / never / if_required / stateless
  sessions: stateless

server:
  tomcat:
    # Write access log to target/logs/access_log.YYYY-MM-DD.log
    # See http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/AccessLogValve.html
    accessLogEnabled: true
    accessLogPattern: '%h %l %u %t "%r" %s %b %{Host}i %{Location}o'
    baseDir: ''
    backgroundProcessorDelay: 1

logging:
  file: logs/application_v3
  level:
    ROOT: WARN
    #org.apache.http: WARN
    #org.springframework: WARN
    #org.springframework.jdbc: WARN
    #org.springframework.security: DEBUG
    com.gospry.api.presentation: INFO
    com.gospry.api: INFO
---

spring:
  profiles: default,staging,production
security:
  require_ssl: true
server:
  # when deployed to CloudFoundry, tomcat is behind a CDN proxy
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

---

spring:
  profiles: default
cache:
  timetolive: 0
---

spring:
  profiles: staging

---

spring:
  profiles: production