project:
  artifactId: spry
  name: spry
  version: 0.5
  description: spry

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  spring:
    profiles: ${spring.profiles.active:default}
  app:
    name: ${vcap.application.name:com.gospry}:${vcap.application.instance_index:*}
    start: ${vcap.application.start:N/A}

spring:
  profiles: default,staging,production
  datasource:
    url: jdbc:mysql://mysql.gospry.com/spry
    username: spry
    password: YnP4K^dD$8J*F&%=
    driver-class-name: com.mysql.jdbc.Driver
  main:
    sources: com.gospry.api.Application
  thymeleaf:
    check-template-location: false
    view-names: status
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
    cache: true
  jpa:
    show_sql: false
    generate-ddl: true
    # org.hibernate.dialect.MySQL5InnoDBDialect or org.hibernate.dialect.HSQLDialect com.gospry.api.helper.HSQLDBDialect
    # FIX to remove error messages
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    connection:
      autoReconnect: true
      autoReconnectForPools: true
#  jpa.hibernate:


server:
  port: 8443
  ssl:
    key-store: classpath:api.gospry.jks
    key-store-password: Bubendorf14
    key-password: Bubendorf14


security:
  require_ssl: true
#  basic:
#    enabled: true
#  require_ssl: false
#  enable_csrf: false
#  ignored:
#    - /register/**
#    - /acitivate/**
#    - /status
#  # always / never / if_required / stateless
#  sessions: stateless

#
# ERROR, WARN, INFO, DEBUG or TRACE
#

logging:
  file: logs/application_v3
  level:
    ROOT: WARN
    org.apache.http: WARN
#    org.springframework: WARN
#    org.springframework.jdbc: WARN
#    org.springframework.security: INFO
#    com.gospry.api.presentation: INFO
    com.gospry.api: TRACE

cache:
  timetolive: 0
